### ISSUE TITLE
Failed to create ".": mkdir(): File exists

### ISSUE THREAD

**Issue by theseer** [MontealegreLuis/phuml#12]
When trying to give phuml a run against phive like this, I get the above error:

```
theseer@nyda /tmp/x5 $ php ./tools/phuml phuml:diagram -r -p neato  ~/storage/php/phar.io/phive/src ./test.png
[|] Running... (This may take some time)
[|] Parsing codebase structure
[|] Running 'Graphviz' processor
[|] Running 'Neato' processor
[|] Writing generated data to disk

In Filesystem.php line 97:
                                              
  Failed to create ".": mkdir(): File exists  
                                              
```

I'm not sure what to do to avoid that from happening :)

**Comment by MontealegreLuis** [comment]
Hi @theseer! thank you for giving phUML a try! 

It means a lot to me. I'm a big fan of your work in the PHP community.

I think I never tried to use absolute/relative paths for the output file, all my examples created a file in the current directory.

I have opened this MR:  https://github.com/MontealegreLuis/phuml/pull/14. 
If you try that branch it should let you save to `./test.png`

**Comment by MontealegreLuis** [comment]
Hi @theseer [5.2.1](https://github.com/MontealegreLuis/phuml/releases/tag/5.2.1) should solve this issue.

**Comment by theseer** [comment]
Confirmed. Thanks!
