### ISSUE TITLE
Creating UML for large project causes wierd image scalling issue

### ISSUE THREAD

**Issue by rainmanjam** [MontealegreLuis/phuml#17]
Working on a large project, phuml causes a scaling issue with the UML generation. Image below. The resolution of the image is 32767 × 617
![test](https://user-images.githubusercontent.com/181322/138209207-14086d14-f5ff-4a2b-9b43-c4f3e71d0d4b.png)

**Comment by MontealegreLuis** [comment]
Hi @rainmanjam we're not passing many configuration options to `neato` or `dot`

Here you can find the options for the generated Digraph: https://github.com/MontealegreLuis/phuml/blob/master/src/resources/templates/digraph.html.twig#L5-L7

And the command is called with `png` as the output file type: https://github.com/MontealegreLuis/phuml/blob/master/src/Processors/ImageProcessor.php#L66

One thing you could try is to generate a `.gv` file and see if other options would generate a better output: https://montealegreluis.com/phuml/docs/dot-file.html

Whether we pass different settings to the `DOT` digraph or different flags to `dot` or `neato` commands.

Maybe the `scale` flag can help: https://www.graphviz.org/doc/info/command.html#-s

If you can share the `.gv` file I could try a few more things as well.
