### ISSUE TITLE
pubkey not found.

### ISSUE THREAD

**Issue by Abhinav1217** [MontealegreLuis/phuml#2]
I am trying to download and use phar, since at the moment, I am not allowed to use composer. When I try to download `wget https://montealegreluis.com/phuml/phuml.phar.pubkey` It is getting 404 error. I tried url on the browser and it is showing github 404 page error. Please update the location of your public key, because without it, the app dosn't work, it gives fatal error.
```
PHP Fatal error:  Uncaught PharException: phar "/home/abhinav/Projects/Rev/phuml.phar" openssl signature could not be verified: openssl public key could not be read in /home/abhinav/Projects/Rev/phuml.phar:9
Stack trace:
#0 /home/abhinav/Projects/Rev/phuml.phar(9): Phar::mapPhar('default.phar')
#1 {main}
  thrown in /home/abhinav/Projects/Rev/phuml.phar on line 9
```

**Comment by MontealegreLuis** [comment]
Hey @Abhinav1217 I added the key back. 

I just tested the installation steps. You shouldn't have that problem anymore
