### ISSUE TITLE
Spread Arguments

### ISSUE THREAD

**Issue by kingga** [MontealegreLuis/phuml#4]
![image](https://user-images.githubusercontent.com/20036047/65561239-d6e58d00-df95-11e9-8918-93c29297af3f.png)

```php
public function __construct(IDatabaseConfig ...$dbconfigs)
```

Should this be displayed as `$dbconfigs: IDatabaseConfig[]`

**Comment by MontealegreLuis** [comment]
Hi @kingga I have added support for variadics in this release: https://github.com/MontealegreLuis/phuml/releases/tag/3.0.0

It includes support for variadics as well as by reference parameters.

Variadic parameters will render as `...$dbconfigs: IDatabaseConfig`. I understand they're technically an array, but wanted to make a distinction between them and methods that receive an actual array.
