### ISSUE TITLE
Download page is 404?

### ISSUE THREAD

**Issue by mosbth** [MontealegreLuis/phuml#5]
I am trying to download the phuml phar as explained in the README.

```
$ wget https://montealegreluis.com/phuml/phuml.phar
```

I get a 404 on that link. 

You can try it out like this:

```
$ curl --silent -I https://montealegreluis.com/phuml/phuml.phar | head -2  
HTTP/2 404                                                                 
date: Mon, 19 Apr 2021 14:39:37 GMT                                        
```

Or just visit the link https://montealegreluis.com/phuml/phuml.phar and it shows you a 404 page.

The main page https://montealegreluis.com/ seems to work.

**Comment by MontealegreLuis** [comment]
Hi @mosbth I have added a Docker image as temporary replacement for the PHAR.

```bash
docker pull montealegreluis/phuml:2.0.0
docker run --rm -v $PWD:/code montealegreluis/phuml phuml:diagram -r -a -i -o -p dot src example.png
```

I'd like to provide a PHAR in a future release through [PHIVE](https://github.com/phar-io/phive) to avoid running into this kind of issues

**Comment by MontealegreLuis** [comment]
Hi @mosbth, phUML can now be install via [PHIVE](https://phar.io/)

```
phive install phuml
```

Closing this, feel free to re-open if you face any other related issue.
